{
 "title": "DB PostgreSQL",
 "tags": [
  "postgres",
  "sql",
  "linux"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB role",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "PostgreSQL: Replication: Recovery role"
       },
       "itemTag": { "filter": "component: replication" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "PostgreSQL uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "PostgreSQL: Uptime" },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Cache hit ratio",
     "type": "stat",
     "description": "Процент запросов к данным, которые были удовлетворены из оперативной памяти (буферного кеша), без необходимости чтения с диска",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "PostgreSQL: Cache hit ratio, %" },
       "itemTag": { "filter": "component: cache" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Patroni active state",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "patroni.service: Active state" },
       "itemTag": { "filter": "component: service" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Patroni active time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "patroni.service: Active time" },
       "itemTag": { "filter": "component: service" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Age of oldest xid",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "PostgreSQL: Age of oldest xid" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Etcd active state",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "ETCD VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "etcd.service: Active state" },
       "itemTag": { "filter": "component: service" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Etcd active time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "ETCD VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "etcd.service: Active time" },
       "itemTag": { "filter": "component: service" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Pgbouncer active state",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "bottom",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "last"
         ],
         "text": "bottom(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+): HAProxy ([^:]+): Server is active$/",
          "$2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "HAProxy INFRA" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "/HAProxy pgbouncer-infra .*: Server is active/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes received",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "WAL: Bytes received" },
       "itemTag": { "filter": "component: wal" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bytes written",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 3 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "WAL: Bytes written" },
       "itemTag": { "filter": "component: wal" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Segments count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 3 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "WAL: Segments count" },
       "itemTag": { "filter": "component: wal" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Dbstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows inserted p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Rows inserted per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Rows returned p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Rows returned per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Hit blocks read p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 2 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Hit blocks read per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Rows deleted p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Rows deleted per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Rows updated p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 6 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Rows updated per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk blocks p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 6 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Disk blocks read per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Backends connected",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Dbstat: Backends connected" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Number temp bytes p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 10 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Number temp bytes per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Committed transactions p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 10 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Dbstat: Committed transactions per second"
       },
       "itemTag": { "filter": "component: transactions" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/(L|l)ag/" },
       "itemTag": { "filter": "component: replication" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Detected deadlocks p/s",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 14 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/dead/" },
       "itemTag": { "filter": "component: deadlocks" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Autovacuum Workers",
     "type": "timeseries",
     "description": "Количество активных autovacuum воркеров",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 14 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/autovac/" },
       "itemTag": { "filter": "component: system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database size",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "100",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/.*\\[\\s*([^\\]]+)\\s*\\]:.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/DB .*: Database size/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Database age",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "100",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/.*\\[\\s*([^\\]]+)\\s*\\]:.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/DB .*: Database age/" },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Database size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "100",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/.*\\[\\s*([^\\]]+)\\s*\\]:.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/DB .*: Database size/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space utilization stats",
     "type": "table",
     "gridPos": { "h": 18, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "17",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/([^:]+: [^:]+):.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Space utilization psqdb-01",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "uxp-psqdb-01" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Space utilization psqdb-02",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "uxp-psqdb-02" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "/pgwal space",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/pgwal: Used space" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "/pgdata: space",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/pgdata: Used space" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Space utilization psqdb-03",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "uxp-psqdb-03" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "/pglog: space",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/pglog: Used space" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "TOP VMs system metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space Utilization",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Space.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/: Space utilization" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: Memory utilization" },
       "itemTag": { "filter": "component: memory" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: CPU utilization" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": true,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": true
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux: Number of processes/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: Number of processes" },
       "itemTag": { "filter": "component: system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ICMP response time",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: ICMP: ICMP response time/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "ICMP: ICMP response time" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
     "options": {
      "content": "Больше информации\r\n## Системные метрики\r\n  \r\n  \r\nМожно посмотреть <a href=\"https://grafana.internal.ru/d/de3maczwcp4owf/vm-linux?orgId=1\" target=\"_blank\"><strong>тут</strong></a>"
     },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits received",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits received/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits sent",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "table",
     "description": "При случайном чтении нормальные значения — 10-50 rd/s. \nВыше 50 rd/s — высокая нагрузка.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk read rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "table",
     "description": "При случайной записи нормальные значения — 50-100 wr/s. Значения выше 100 wr/s считаются высокими и могут указывать на: перегрузку диска, неоптимизированные запросы (например, мелкие записи), проблемы с кэшированием.\n\nПостоянные >200 wr/s — часто недостаток RAM (частая запись на диск из-за нехватки буферов).\n",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk write rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Connections, locks & queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active connections",
     "type": "timeseries",
     "description": "Количество активных подключений",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 23 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Connections sum: Active" },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Connections Idle",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 23 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Connections sum: Idle" },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Connections total",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 23 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Connections sum: Total" },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Waiting сonnections",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 27 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Connections sum: Waiting" },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Connections Idle in transaction",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 27 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Connections sum: Idle in transaction"
       },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Connections total %",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 27 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Connections sum: Total, %" },
       "itemTag": { "filter": "component: connections" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Tuples inserted",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 31 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Tuples inserted/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Tuples deleted",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 31 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/.*Tuples deleted per second/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Tuples fetched ",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 31 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Tuples fetched/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Tuples returned",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 35 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/.* Tuples .*/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Tuples updated",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 35 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Tuples updated/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Slow queries",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 35 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "PostgreSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Queries slow/" },
       "itemTag": { "filter": "component: queries" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  }
 ]
}