{
 "title": "MS Exchange",
 "tags": [
  "exchange",
  "mail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ActiveSync: ping command pending",
     "type": "stat",
     "description": "Количество команд PING для ActiveSync, ожидающих обработки.  \n- 0 - идеально  \n- 1-5 - допустимо   ",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: ActiveSync: ping command pending"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/CPU utilization/" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": true,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": true
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Bits received",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits received/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows: Number of processes/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Windows: Number of processes" },
       "itemTag": { "filter": "component: os" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
     "options": {
      "content": "Системные метрики серверов можно посмотреть <a href=\"https://grafana.internal.ru/d/de34tk8e82a68a/vm-windows?orgId=1\" target=\"_blank\"><strong>тут</strong></a>\r\n"
     },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ActiveSync: sync commands p/s",
     "type": "timeseries",
     "description": "Количество команд синхронизации ActiveSync",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: ActiveSync: sync commands per second"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Memory utilization/" },
       "itemTag": { "filter": "component:memory" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits sent",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ICMP response time",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: ICMP: ICMP response time/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "ICMP: ICMP response time" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ActiveSync: requests p/s",
     "type": "timeseries",
     "description": "Общее количество запросов ActiveSync",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: ActiveSync: requests per second"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Space Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Space.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        },
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "table",
     "description": "При случайном чтении нормальные значения — 10-50 rd/s. \nВыше 50 rd/s — высокая нагрузка.",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk read rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "table",
     "description": "При случайной записи нормальные значения — 50-100 wr/s. Значения выше 100 wr/s считаются высокими и могут указывать на: перегрузку диска, неоптимизированные запросы (например, мелкие записи), проблемы с кэшированием.\n\nПостоянные >200 wr/s — часто недостаток RAM (частая запись на диск из-за нехватки буферов).\n",
     "gridPos": { "h": 6, "w": 3, "x": 17, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk write rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "OWA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active mailboxes count",
     "type": "timeseries",
     "description": "Общее количество активных почтовых ящиков на сервере.",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 21 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Information Store [_total]: Active mailboxes count"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Outlook requests p/s",
     "type": "timeseries",
     "description": "Количество HTTP-запросов к Outlook Web App в секунду.",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 21 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: Outlook Web App: requests per second"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "WebSite current connections",
     "type": "timeseries",
     "description": "Current connections измеряет:\nТекущее количество HTTP-подключений к Default Web Site — клиентские подключения (OWA, ECP, ActiveSync).\n\nРезкий рост может указывать на:\n- DDoS-атаку\n- Утечку соединений (например, из-за зависших сессий)",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 25 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Web Service [Default Web Site]: Current connections"
       },
       "itemTag": { "filter": "component: web" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "BackEnd current connections",
     "type": "timeseries",
     "description": "Текущее количество HTTP внутренних запросов между сервисами Exchange.",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 25 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Web Service [Exchange Back End]: Current connections"
       },
       "itemTag": { "filter": "component: web" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Availability Service: requests p/s",
     "type": "timeseries",
     "description": "Запросы к службе проверки доступности (для календарей)",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 29 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: Availability Service: availability requests per second"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Autodiscover: requests p/s",
     "type": "timeseries",
     "description": "Количество запросов к службе Autodiscover в секунду (используется клиентами для автоматической настройки).\n\nРезкие скачки могут указывать на:\n* Массовое переподключение клиентов (например, после сбоя)\n* Атаку типа Brute Force (если запросы идут с необычных IP)",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 29 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange [Client Access Server]: Autodiscover: requests per second"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Domain Controller read/search time",
     "type": "timeseries",
     "description": "/Domain Controller/",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 33 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "MSP-EXCAP-01" },
       "item": { "filter": "/Domain Controller/" },
       "itemTag": { "filter": "component: ldap" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Database Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Databases total mounted",
     "type": "stat",
     "description": "Количество смонтированных баз данных.  \nДолжно соответствовать ожидаемому количеству.  \nЛюбое уменьшение - критично.",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MS Exchange: Databases total mounted"
       },
       "itemTag": { "filter": "component: application" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Page faults p/s",
     "type": "timeseries",
     "description": "Количество ошибок страниц памяти в секунду.",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 20 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Information Store [_total]: Page faults per second"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Database copy role",
     "type": "stat",
     "description": "Роль копии БД (1=Active, 2=Passive, 3=Lagged).  \nДля каждого DAG должна быть ровно 1 активная копия.  \nНеожиданное изменение - критично.",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Active Manager [_total]: Database copy role"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Log records stalled",
     "type": "timeseries",
     "description": "Количество задержанных записей в логах.",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 24 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Information Store [_total]: Log records stalled"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Active DB r/o per second",
     "type": "timeseries",
     "description": "Database Counters [_total]: Active database read operations per second",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 28 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Database Counters [_total]: Active database read operations per second"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Active DB w/o per second",
     "type": "timeseries",
     "description": "Database Counters [_total]: Active database write operations per second",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 28 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Database Counters [_total]: Active database write operations per second"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Active DB r/o latency",
     "type": "timeseries",
     "description": "Database Counters [_total]: Active database read operations latency",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 32 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Database Counters [_total]: Active database read operations latency"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Active DB w/o latency",
     "type": "timeseries",
     "description": "Database Counters [_total]: Active database write operations latency",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 32 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Database Counters [_total]: Active database write operations latency"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "RPC requests  p/s",
     "type": "timeseries",
     "description": "Information Store [_total]: RPC requests per second",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 36 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Information Store [_total]: RPC requests per second"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "RPC requests latency",
     "type": "timeseries",
     "description": "Information Store [_total]: RPC requests latency",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 36 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Exchange VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Information Store [_total]: RPC requests latency"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}