{
 "title": "DB MS SQL",
 "tags": [
  "database",
  "sql",
  "microsoft"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "12",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/^([^:]+):.*$/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "MSSQL: Uptime" },
     "itemTag": { "filter": "component: application" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "Больше информации\r\n## Системные метрики\r\n  \r\n  \r\nМожно посмотреть <a href=\"https://grafana.internal./d/de34tk8e82a68a/vm-windows?orgId=1\" target=\"_blank\"><strong>тут</strong></a>"
   },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: .*/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Bits sent/" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "DB role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "12",
        "avg"
       ],
       "text": "bottom(5, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/^([^:]+):.*$/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Role/" },
     "itemTag": { "filter": "component: replica" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "AG Synchronization health",
   "type": "stat",
   "description": "Reflects a rollup of the database synchronization state (synchronization_state) of all joined availability databases (also known as replicas) and the availability mode of the replica (synchronous-commit or asynchronous-commit mode).   \n\nThe rollup will reflect the least healthy accumulated state of the databases on the replica:\n0 = Not healthy. At least one joined database is in the \"Not synchronizing\" state.\n1 = Partially healthy. Some replicas are not in the target synchronization state: synchronous-commit replicas should be synchronized, and asynchronous-commit replicas should be synchronizing.\n2 = Healthy. All replicas are in the target synchronization state: synchronous-commit replicas are synchronized, and asynchronous-commit replicas are synchronizing.",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "24",
        "avg"
       ],
       "text": "bottom(5, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/^MSP-(MSQDB-\\d+(?:_\\w+)?): MSSQL AG 'MSP-MSQDB-(AG\\d+)' Replica 'MSP-MSQDB-(\\d+)(\\\\\\w+)?': Sync health$/",
        "$1-$2-$3$4"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/MSSQL AG.*': Sync health/" },
     "itemTag": { "filter": "component: replica" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Space Utilization",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Space.*/",
        "$'"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Space utilization/" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "4",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Windows.*/",
        "$'"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Memory utilization/" },
     "itemTag": { "filter": "component:memory" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "4",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Windows.*/",
        "$'"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/CPU utilization/" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP response time",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "4",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: ICMP: ICMP response time/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP: ICMP response time" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "4",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Windows: Number of processes/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Windows: Number of processes" },
     "itemTag": { "filter": "component: os" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Disk read rate",
   "type": "table",
   "description": "При случайном чтении нормальные значения — 10-50 rd/s. \nВыше 50 rd/s — высокая нагрузка.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Disk read rate/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Disk read rate/" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Disk write rate",
   "type": "table",
   "description": "При случайной записи нормальные значения — 50-100 wr/s. Значения выше 100 wr/s считаются высокими и могут указывать на: перегрузку диска, неоптимизированные запросы (например, мелкие записи), проблемы с кэшированием.\n\nПостоянные >200 wr/s — часто недостаток RAM (частая запись на диск из-за нехватки буферов).\n",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: Disk write rate/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Disk write rate/" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Bits received",
   "type": "table",
   "description": "10000000 - 10МБ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: .*/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Bits received/" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Bits sent",
   "type": "table",
   "description": "10000000 - 10МБ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "/Filesystem./" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "3",
        "last"
       ],
       "text": "top(5, avg)"
      },
      {
       "$$hashKey": "object:3501",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: .*/",
        "$'"
       ],
       "text": "replaceAlias(/: Space utilization/, $')"
      }
     ],
     "group": { "filter": "MSSQL VMs" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Bits sent/" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors per second",
     "type": "stat",
     "gridPos": { "h": 4, "w": 21, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "12",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/MSSQL: Errors per second/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Errors per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 6 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "12",
          "last"
         ],
         "text": "top(5, avg)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/MSSQL: Errors per second/" },
       "itemTag": { "filter": "component: error" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Dbstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": " Memory page faults p/s",
     "type": "stat",
     "description": "Количество ошибок страниц в секунду.   \nВысокий показатель может указывать на нехватку оперативной памяти или интенсивное использование дискового пространства для виртуальной памяти.",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "Windows: Memory page faults per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Paging File",
     "type": "stat",
     "description": "Процент свободного места в файле подкачки.   \nЕсли значение низкое, система близка к исчерпанию памяти. Это может привести к замедлению работы.",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "asc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Windows: Free swap space in %" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "CPU privileged time",
     "type": "stat",
     "description": "Доля времени, в течение которого процессор работает в привилегированном (режим ядра) режиме, выполняя системные операции. Высокий показатель может указывать на интенсивную системную активность или проблемы с производительностью",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Windows: CPU privileged time" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DB State",
     "type": "table",
     "description": "Сначала UP\n",
     "gridPos": { "h": 15, "w": 7, "x": 0, "y": 7 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+): MSSQL DB '([^']+)'.*$/",
          "$1 $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/MSSQL .*: State/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Page life expectancy",
     "type": "table",
     "description": "Время жизни страниц в кэше (сек)",
     "gridPos": { "h": 15, "w": 7, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "bottom",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "20",
          "last"
         ],
         "text": "bottom(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^MSP-MSQDB-([^:]+):.+$/",
          "MSP-MSQDB-$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "MSSQL: Page life expectancy" },
       "itemTag": { "filter": "component: page" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Buffer cache hit ratio %",
     "type": "table",
     "description": "Процент попаданий в кэш буфера\n",
     "gridPos": { "h": 15, "w": 7, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "bottom",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "20",
          "last"
         ],
         "text": "bottom(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^MSP-MSQDB-([^:]+):.+$/",
          "MSP-MSQDB-$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "MSSQL: Buffer cache hit ratio" },
       "itemTag": { "filter": "component: cache" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active transactions",
     "type": "timeseries",
     "description": "Количество текущих транзакций в базе данных.",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "/MSSQL DB .*: Active transactions/"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Compilations  p/s",
     "type": "timeseries",
     "description": "Компиляций T-SQL в секунду",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 4 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/compilations/" },
       "itemTag": { "filter": "component: performance" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Batch requests p/s",
     "type": "timeseries",
     "description": "Запросов в секунду",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 4 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MSSQL: Batch requests per second"
       },
       "itemTag": { "filter": "component: performance" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Page splits per second",
     "type": "timeseries",
     "description": "Количество операций разделения страниц в секунду.   \nВысокий показатель указывает на фрагментацию данных и может привести к снижению производительности базы данных.",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "MSSQL: Page splits per second" },
       "itemTag": { "filter": "component: performance" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": " Lazy Writes p/s",
     "type": "timeseries",
     "description": "Количество операций отложенной записи данных на диск в секунду. Высокий показатель может указывать на нехватку оперативной памяти или высокую нагрузку на базу данных",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 10 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "MSSQL: Lazy writes per second" },
       "itemTag": { "filter": "component: performance" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Data file size",
     "type": "piechart",
     "description": "Общий размер файлов базы данных на диске",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Data file/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Log backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last log backup",
     "type": "stat",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "12",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Last log backup/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Last log backup time ago",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "100",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^(MSP-MSQDB-[^:]+): MSSQL DB '((.{1,30})(?=_|$)|([^']+))'.*$/",
          "$1: $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "/Last log backup \\(time ago\\)/"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Last full backup",
     "type": "stat",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "12",
          "first"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [ "asc" ],
          "name": "sortSeries",
          "params": [
           {
            "name": "direction",
            "options": [
             "asc",
             "desc"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "desc" ],
         "text": "sortSeries(asc)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^([^:]+):.*$/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Last full backup/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Last full backup time ago",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 9, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "100",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^(MSP-MSQDB-[^:]+): MSSQL DB '((.{1,30})(?=_|$)|([^']+))'.*$/",
          "$1: $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "/Last full backup \\(time ago\\)/"
       },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Logs & locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log growths",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "3",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^MSP-MSQDB-([^:]+): MSSQL DB '(.{1,16})[^']*'.*$/",
          "$1  $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log growths/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Log bytes flushed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log bytes flushed/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Log flushes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log flushes/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Percent log used",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "10",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^MSP-MSQDB-([^:]+): MSSQL DB '(.{1,16})[^']*'.*$/",
          "$1  $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Percent log used/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Percent log used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Percent log used/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Log file size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 12 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log file size/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Log shrinks",
     "type": "stat",
     "description": "Количество операций сжатия журнала\nНорма: 0-1 в день, высокие значения указывают на проблемы с настройкой",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "10",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^MSP-MSQDB-([^:]+): MSSQL DB '(.{1,16})[^']*'.*$/",
          "$1  $2"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log shrinks/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total lock requests p/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 18 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MSSQL: Total lock requests per second"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total lock requests timeout",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 18 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": {
        "filter": "MSSQL: Total lock requests per second that timed out"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "MSP-MSQDB-01",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "MSP-MSQDB-01" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "MSP-MSQDB-02",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "MSP-MSQDB-02" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "MSP-MSQDB-03",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "MSP-MSQDB-03" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Log file size",
     "type": "table",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "50",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/([^:]+: [^:]+):.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Log file size/" },
       "itemTag": { "filter": "component: database" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Space utilization stats",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "17",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/([^:]+: [^:]+):.*/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk average queue size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 19 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "MSSQL VMs" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk average queue size/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "{$MSSQL.PASSWORD}" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}