{
 "title": "VMs TOP",
 "description": "An easy way to view the performance of your servers",
 "tags": [
  "zabbix",
  "all",
  "linux",
  "windows"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Linux_hosts",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Windows TOP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Spac.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Space utilization/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Memory utilization/" },
       "itemTag": { "filter": "component: memory" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3582",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows.*/",
          "$'"
         ],
         "text": "replaceAlias(/: CPU utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/CPU utilization/" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Windows: Number of processes/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Windows: Number of processes" },
       "itemTag": { "filter": "component: os" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ICMP response time",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: ICMP: ICMP response time/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "ICMP: ICMP response time" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits received",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits received/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits sent",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "table",
     "description": "При случайном чтении нормальные значения — 10-50 rd/s. \nВыше 50 rd/s — высокая нагрузка.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk read rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "table",
     "description": "При случайной записи нормальные значения — 50-100 wr/s. Значения выше 100 wr/s считаются высокими и могут указывать на: перегрузку диска, неоптимизированные запросы (например, мелкие записи), проблемы с кэшированием.\n\nПостоянные >200 wr/s — часто недостаток RAM (частая запись на диск из-за нехватки буферов).",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/:: Disk write rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": { "filter": "Windows servers" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Linux TOP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Space.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/: Space utilization" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: Memory utilization" },
       "itemTag": { "filter": "component: memory" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux.*/",
          "$'"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: CPU utilization" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": true,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": true
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Linux: Number of processes/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Linux: Number of processes" },
       "itemTag": { "filter": "component: system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "ICMP response time",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: ICMP: ICMP response time/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "ICMP: ICMP response time" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits received",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits received/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Bits sent",
     "type": "table",
     "description": "10000000 - 10МБ",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: .*/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Bits sent/" },
       "itemTag": { "filter": "component: network" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk read rate",
     "type": "table",
     "description": "При случайном чтении нормальные значения — 10-50 rd/s. \nВыше 50 rd/s — высокая нагрузка.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk read rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk read rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Disk write rate",
     "type": "table",
     "description": "При случайной записи нормальные значения — 50-100 wr/s. Значения выше 100 wr/s считаются высокими и могут указывать на: перегрузку диска, неоптимизированные запросы (например, мелкие записи), проблемы с кэшированием.\n\nПостоянные >200 wr/s — часто недостаток RAM (частая запись на диск из-за нехватки буферов).\n",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "application": { "filter": "/Filesystem./" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "4",
          "last"
         ],
         "text": "top(5, avg)"
        },
        {
         "$$hashKey": "object:3501",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/: Disk write rate/",
          "$'"
         ],
         "text": "replaceAlias(/: Space utilization/, $')"
        }
       ],
       "group": {
        "filter": "/AWX VMs|DION VMs|ETCD VMs|FreeIPA VMs|Gitlab VMs|Gluster FS VMs|Grafana VMs|HAProxy VMs|HCL Linux|KSMG VMs|Keycloak VMs|MFA VMs|NTP VMs|Netbox VMs|Nexus VMs|PAM Linux|PDNS VMs|PostgreSQL VMs/"
       },
       "host": { "filter": "/.*/" },
       "item": { "filter": "/Disk write rate/" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "History & Problems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "History",
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 21 },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "evaltype": "0",
       "group": { "filter": "/(Linux|Windows) servers/" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Perda de Pacotes" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "severities": [],
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "showProblems": "history",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2, "minSeverity": 0 }
      }
     ]
    }
   ]
  }
 ]
}